### ISSUE TITLE
Dosent load script in Firefox

### ISSUE THREAD

**Issue by gut8er** [Jersyfi/Cookify#10]
After page load in Firefox i have this in the DOM

<script data-c-script="marketing" type="text/javascript" src="https://integrations.etrusted.com/applications/widget.js/v2"></script>
<script data-c-script="performance" type="text/javascript" src="https://www.google-analytics.com/plugins/ua/ecommerce.js"></script>

But its not loaded :( It works in Chorme and Edge. I have no errors in my console. The type="text/plain" is set correctly in the code. I have no idea... Has anyone an idea what i can try?

**Comment by Jersyfi** [comment]
@gut8er i will check your issue and then answer you shortly.

**Comment by Jersyfi** [comment]
@gut8er 
Check out version v3.0.2 and tell me if everything is working

https://github.com/Jersyfi/Cookify/releases/tag/v3.0.2
