### ISSUE TITLE
Google Analytics scripts in the <head> tag

### ISSUE THREAD

**Issue by itinchev** [Jersyfi/Cookify#13]
Hello,

First of all, thank you for providing this tool. It looks and works great.
The only important problem I have and I am trying to solve is concerning the requirement of Google Analytics remote source code. They say, I quote, "Copy and paste this code as the first item into the `<HEAD>` of every webpage you want to track." So I am placing the code right after `<head>` adding the `data-c-script="statistics"` as cookies category to the 2 `<script>` tags.

![image](https://user-images.githubusercontent.com/43116344/195364296-c27ede1a-4395-4f81-9ea2-0917d9797313.png)

However, the Analytics code loads anyway because it is the first script in the head. Or I am missing something...

**Comment by Jersyfi** [comment]
Hi @itinchev, thank you for using Cookify 👍🏼 In the first script you need to add `type="text/plain"` to it. In the second one you need to change `type="text/javascript"` to `type="text/plain"`. Then you are ready to go.

```html
<script type="text/plain" async src="https://www.googletagmanager.com/gtag/js?id=UA-XXX" data-c-script="statistics"></script>
<script type="text/plain" data-c-script="statistics">
   window.dataLayer = window.dataLayer || [];
   function gtag() {dataLayer.push(arguments);}
   gtag('js', new Date());
   gtag('config', 'UA-XXX');
</script>
```

**Comment by itinchev** [comment]
Thank you, @Jersyfi!
This solved the issue. As I said, great tool, but also great support and responsible person behind it. Keep up the good work!

**Comment by Jersyfi** [comment]
Thank you for your words 👍
