### ISSUE TITLE
The module does not work on Microsoft Edge

### ISSUE THREAD

**Issue by denracom** [Jersyfi/Cookify#5]
Hello,

First of all: Great code and features. Congrats!

The issue: When Cookiefy is implemented in a website as described in the documentation it runs without problems on Chrome, Firefox and Opera, but does not work on Edge (Microsoft Edge 44.19041.423.0, Microsoft EdgeHTML 18.19041). No error is displayed. The cookie icon and the model do not appear.

Thank you in advance for your help.

**Comment by Jersyfi** [comment]
Thank you for your issue.

I am constantly testing in Microsoft Edge. For me it is working normally like in all other browsers.
Make sure you have the latest update of Microsoft Edge. I have the version 88.0.705.56.

**Comment by denracom** [comment]
Thank you for your prompt reply, @Jersyfi.
You are right. It works perfectly with the newest version. Unfortunately, it seems that the other version I have used to test before was too old. Thanks again for the great scripts.
