### ISSUE TITLE
Support for scripts inside the HTML file.

### ISSUE THREAD

**Issue by PrimozGodec** [Jersyfi/Cookify#6]
@Jersyfi thank you for a great library. I like its simplicity. It works great with the external script:
```
<script type="text/plain" src="..." />
```
but for me it does not work with script inside the HTML (such as google analytics):
```
<script type="text/plain" cookify="analytics">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', <GATAG>);
</script>
```
It changes type to `"text/plain"` and it sets `src=null`. From the source code, it looks like it is made only for the external script. I am asking if there is any option to handle scripts in the file too or should I move my Google Analytics snippet to a separate file?

**Comment by Jersyfi** [comment]
@PrimozGodec thank you for reporting this issue 👍🏼
You are right with your description.
Let me think about a quick fix for the old version, because i am working on version 3.

I'll hope to quickly respond to your Issue.

**Comment by PrimozGodec** [comment]
Thank you for your very fast response. It is nice to hear that version 3 is coming. :) 

I tried to come up with the solution for inline javascript but do not have an idea now. With a regular script this code (if I understand right) make the script execute:
https://github.com/Jersyfi/Cookify/blob/b9d555779199c21dd49d6834d8bce14893288a75/cookify.js#L945-L947
But I do not have an idea how to dynamically execute the inline javascript after replacing the type. Do you have any?

**Comment by Jersyfi** [comment]
@PrimozGodec sorry for my late reply with a solution.
I was busy with my exams so this was my priority.

Finally i got a solution for this issue please try if it works in your case.
https://github.com/Jersyfi/Cookify/releases/tag/v2.1.1

**Comment by PrimozGodec** [comment]
Thank you for a solution and no problem for wait. It seems it works for me. @Jersyfi good luck with exams. :)

**Comment by Jersyfi** [comment]
@PrimozGodec Thank you.

Check out Version 3 of Cookify. It is more simple and you have the option for tracking user activity. I also made a bootstrap test file. But in version 3 you need to build the html on your own. I think it is better because you must not use specific bootstrap like in version 2.

**Comment by PrimozGodec** [comment]
I didn't notice that you already released version 3. I will test it out. Thank you for letting me know.
