### ISSUE TITLE
QUESTION: How can I trap the acceptance event?

### ISSUE THREAD

**Issue by carlosalvidrez** [Jersyfi/Cookify#9]
Thanks for sharing your work!

I need to persist the agreement in a database, and so I wonder if you might be able to create a hook, or provide an example on how I could mount a listener, so I can act upon user action.

**Comment by Jersyfi** [comment]
I am working on Version 3 where I included the tracking function already. This Version is more simple and you can chosse the CSS framework on your own and just add a few lines of code. I started the documentation already but it is not finished. Maybe check it out and help me to finish this Version. When you want to test it without coding then go in the test directory and use the bootstrap.html file.

Link to version 3: https://github.com/Jersyfi/Cookify/tree/v3

In case this version does not fit your needs tell me what you exactly need or what you are missing.

**Comment by carlosalvidrez** [comment]
Thanks Jersyfi, I'd need to see an example on how to trap the event, so I can then do something when the user accepts (or does not accept) cookies. If you could add one to your documentation, I think your project will stand out more from the others. 

It'd be good for me, for regulatory reasons to not rely on the client's existence of a cookie, but to, in addition, also know at which date and time they agreed, and which types of cookies they agreed to. Hope that makes sense.

**Comment by Jersyfi** [comment]
Yes that is a good point. I will work on that tomorrow.
Is the Bootstrap example working for you and can you reed out the data in the console?

**Comment by Jersyfi** [comment]
I added only the date to the tracking Callback function. It is on your own what you will do with this funtion and how you ganerate a unique ID.

Also i wrote an example on how to write the tracking callback function. This example outputs the values in the console. What you do with the data and how you are going to store it is on your own.

![image](https://user-images.githubusercontent.com/64214261/118261462-dde74900-b4b3-11eb-9897-17ad0f610d24.png)

Try out the test file bootstrap.html to see what you can do.

**Comment by carlosalvidrez** [comment]
Suggestion: add also the type of cookies and the user selected value. It is important to know if they were accepted or not (each kind… necessary cookies, marketing cookies, etc).

Thanks!

**Comment by Jersyfi** [comment]
If you had tested the bootstrap.html file, you would have seen that the data would already have included the types.
Following i show you the console log that you see when testing the file.

![image](https://user-images.githubusercontent.com/64214261/118358138-c70d2900-b57d-11eb-9227-6d11323ef98b.png)

So again. What you do with this data is your decision. But please don't complain about something without testing it.

**Comment by carlosalvidrez** [comment]
Not complaining. Thanks
